apiVersion: v1
kind: Pod
metadata:
  name: pod6
spec:
  containers:
  - name: pod6
    image: busybox:1.31.0
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 1d;
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 10
